//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class url
    {
        public int id { get; set; }
        public string shortenedURL { get; set; }
        public string url1 { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> clicks { get; set; }
        public Nullable<System.DateTime> lastClick { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string Location { get; set; }
    
        public virtual user user { get; set; }
    }
}
